openapi: 3.0.3
info:
  title: Physical AI & Humanoid Robotics Textbook Frontend API
  description: API for UI/UX features and theme customization in the Physical AI & Humanoid Robotics textbook
  version: 1.0.0
  contact:
    name: Textbook API Support
    email: support@textbook.example.com

servers:
  - url: https://api.textbook.example.com
    description: Production server
  - url: https://staging-api.textbook.example.com
    description: Staging server

paths:
  /themes/current:
    get:
      summary: Get current theme configuration
      description: Retrieve the current theme settings for the user or default settings
      tags:
        - Themes
      parameters:
        - name: user_id
          in: query
          description: Optional user ID to get personalized theme settings
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Current theme configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeConfiguration'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update theme configuration
      description: Update the user's theme preferences
      tags:
        - Themes
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThemeUpdateRequest'
      responses:
        '200':
          description: Theme configuration updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThemeConfiguration'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /visual-elements:
    get:
      summary: Get visual element configurations
      description: Retrieve configurations for UI elements like cards, buttons, etc.
      tags:
        - Visual Elements
      parameters:
        - name: element_type
          in: query
          description: Filter by element type (card, button, navigation, hero, module)
          required: false
          schema:
            type: string
            enum: [card, button, navigation, hero, module]
        - name: page_id
          in: query
          description: Filter by specific page ID to get relevant elements
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of visual element configurations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VisualElement'
        '400':
          $ref: '#/components/responses/BadRequest'

  /animations/floating-robots:
    get:
      summary: Get floating robot animation settings
      description: Retrieve configuration for animated floating robot elements
      tags:
        - Animations
      parameters:
        - name: page
          in: query
          description: Page context for animation settings
          required: false
          schema:
            type: string
            default: "homepage"
      responses:
        '200':
          description: Floating robot animation settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    default: 3
                    description: Number of floating robots to display
                  types:
                    type: array
                    items:
                      type: string
                      enum: [humanoid, industrial, mobile, drone]
                    default: [humanoid, industrial, mobile]
                    description: Types of robots to display
                  settings:
                    $ref: '#/components/schemas/AnimationController'
        '400':
          $ref: '#/components/responses/BadRequest'

  /fonts/available:
    get:
      summary: Get available font options
      description: Retrieve list of available tech fonts for headings and body text
      tags:
        - Fonts
      responses:
        '200':
          description: Available font options
          content:
            application/json:
              schema:
                type: object
                properties:
                  heading_fonts:
                    type: array
                    items:
                      type: string
                    example: ["Orbitron", "Exo 2", "Roboto Mono", "Space Grotesk"]
                  body_fonts:
                    type: array
                    items:
                      type: string
                    example: ["Exo 2", "Inter", "Open Sans", "Roboto"]
                  current_heading:
                    type: string
                    default: "Orbitron"
                  current_body:
                    type: string
                    default: "Exo 2"

  /responsive/layout:
    get:
      summary: Get responsive layout configuration
      description: Retrieve layout settings for different screen sizes
      tags:
        - Responsive
      parameters:
        - name: breakpoint
          in: query
          description: Target breakpoint for layout settings
          required: false
          schema:
            type: string
            enum: [mobile, tablet, desktop, wide]
            default: desktop
      responses:
        '200':
          description: Responsive layout configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsiveLayout'
        '400':
          $ref: '#/components/responses/BadRequest'

  /neon-mode/toggle:
    post:
      summary: Toggle neon mode
      description: Enable or disable enhanced neon visual effects
      tags:
        - Themes
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Whether to enable or disable neon mode
              required:
                - enabled
      responses:
        '200':
          description: Neon mode toggled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                  type: boolean
                  enabled:
                  type: boolean
                  message:
                  type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    ThemeConfiguration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          description: Null for global settings
        theme_mode:
          type: string
          enum: [dark, neon, light]
          default: dark
        accent_color:
          type: string
          default: "#00f0ff"
          description: Primary cyan color
        secondary_color:
          type: string
          default: "#ff2a6d"
          description: Secondary magenta color
        glow_intensity:
          type: number
          format: float
          minimum: 0.0
          maximum: 2.0
          default: 1.0
        animation_enabled:
          type: boolean
          default: true
        font_family_heading:
          type: string
          enum: [Orbitron, Exo 2, system]
          default: Orbitron
        font_family_body:
          type: string
          enum: [Exo 2, Orbitron, system]
          default: Exo 2
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ThemeUpdateRequest:
      type: object
      properties:
        theme_mode:
          type: string
          enum: [dark, neon, light]
        accent_color:
          type: string
          pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
        secondary_color:
          type: string
          pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
        glow_intensity:
          type: number
          format: float
          minimum: 0.0
          maximum: 2.0
        animation_enabled:
          type: boolean
        font_family_heading:
          type: string
          enum: [Orbitron, Exo 2, system]
        font_family_body:
          type: string
          enum: [Exo 2, Orbitron, system]

    VisualElement:
      type: object
      properties:
        id:
          type: string
          format: uuid
        element_type:
          type: string
          enum: [card, button, navigation, hero, module]
        element_id:
          type: string
          description: Specific element identifier if applicable
        glow_effect:
          type: boolean
          default: true
        neon_border:
          type: boolean
          default: true
        hover_animation:
          type: boolean
          default: true
        animation_speed:
          type: string
          enum: [slow, normal, fast]
          default: normal
        color_scheme:
          type: object
          description: Custom color overrides for this element
        settings:
          type: object
          description: Element-specific settings
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    AnimationController:
      type: object
      properties:
        id:
          type: string
          format: uuid
        animation_type:
          type: string
          enum: [floating-robot, glow-pulse, neon-flicker, hover-bounce]
        element_id:
          type: string
          description: Associated UI element ID
        is_active:
          type: boolean
          default: true
        speed_factor:
          type: number
          format: float
          minimum: 0.1
          maximum: 3.0
          default: 1.0
        motion_preference_respected:
          type: boolean
          default: true
        performance_priority:
          type: string
          enum: [performance, balanced, quality]
          default: balanced
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ResponsiveLayout:
      type: object
      properties:
        id:
          type: string
          format: uuid
        breakpoint_target:
          type: string
          enum: [mobile, tablet, desktop, wide]
        layout_type:
          type: string
          enum: [grid, flex, column, row]
        element_adjustments:
          type: object
          description: Specific adjustments for this breakpoint
        font_scaling:
          type: number
          format: float
          default: 1.0
        animation_adaptation:
          type: string
          enum: [maintain, reduce, remove]
          default: maintain
        interaction_modifications:
          type: object
          description: Changes to interactions based on screen size
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "bad_request"
              message:
                type: string
                example: "Invalid request parameters"
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "unauthorized"
              message:
                type: string
                example: "Authentication token is missing or invalid"
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "forbidden"
              message:
                type: string
                example: "Insufficient permissions to perform this action"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "not_found"
              message:
                type: string
                example: "The requested resource was not found"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - BearerAuth: []